[package]
name = "bitcoin_scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.6"
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
hex = "0.4"
env_logger = "0.10"
